<?php
/**
 * Override hook_block_list_alter to hide blocks as per functionality
 */
function customblock_block_list_alter(&$blocks) {
  global $language, $theme_key;

  $node = menu_get_object();

  $opportunityBlockDelta = '632c6a6948db8a6e1abeefffbb2a47e1';
  $analysisBlockDetla = 'c3cc961a461ab144fd61ed14fa2780c4';
  $impactBlockDetla = 'd0c1cfad3aa9a6c2674f7bc1a22ddda2';

  if ( !empty($node) ) {
    if( $node->type == 'article' ) {
      $articleType = $node->field_article_type['und'][0]['taxonomy_term']->name;


      foreach ($blocks as $key => $block) {
        if(strtolower($articleType) == 'opportunities') {
          if(in_array($block->delta, array($analysisBlockDetla, $impactBlockDetla))) {
            unset($blocks[$key]);
          }
        } elseif (strtolower($articleType) == 'analysis') {
          if(in_array($block->delta, array($opportunityBlockDelta, $impactBlockDetla))) {
            unset($blocks[$key]);
          }
        } elseif (strtolower($articleType) == 'impact') {
          if(in_array($block->delta, array($opportunityBlockDelta, $analysisBlockDetla))) {
            unset($blocks[$key]);
          }
        } else {
          if(in_array($block->delta, array($opportunityBlockDelta, $analysisBlockDetla, $impactBlockDetla))) {
            unset($blocks[$key]);
          }
        }
      }
    } else {
      foreach ($blocks as $key => $block) {
        if(in_array($block->delta, array($opportunityBlockDelta, $analysisBlockDetla, $impactBlockDetla))) {
          unset($blocks[$key]);
        }
      }
    }
  }
}

function customblock_views_pre_render(&$view) {
  // Removing 'height' and 'width' attributes of img tag for home page blocks.
  if($view->name == 'home_page_blocks') {
      $viewsList = array(
            'block_3',
            'block_1',
            'block'
        );
      if(in_array($view->current_display, $viewsList)) {
          foreach($view->result as $row) {
            unset($row->field_field_article_image[0]['rendered']['#item']['width']);
            unset($row->field_field_article_image[0]['rendered']['#item']['height']);
          }
      }
  }

  if($view->current_display == 'block_6') {
    foreach($view->result as $row) {
        if(count($row->field_field_article_reference) == 0) {
          $view->build_info['title'] = "";
        } else {
          $view->build_info['title'] = "Related Articles";
        }
        //echo "<pre style='display:none'>"; print_r(count($row->field_field_article_reference)); echo "</pre>";
    }
  }
}

/**
 * Implementation of hook_views_query_alter
 * @param type $view
 * @param type $query
 */
function customblock_views_query_alter(&$view, &$query) {

  // Condition for Sidebar filter on Category Page.
  if ($view->name == 'related_article_for_category') {
    $term_id = arg(2);
    if(!empty($term_id)) {
      $query->where[1]['conditions'][1] = array(
                                  'field' => 'taxonomy_term_data.tid',
                                  'value' => array($term_id),
                                  'operator' =>'NOT IN'
                              );
    }
  }
  if($view->name == 'related_article_for_opportunity') {
    echo 'Here';
  }
}


function customblock_form_alter(&$form, &$form_state, $form_id)
{

  if($form_id == "article_node_form") {
    $form['body'][LANGUAGE_NONE][0]['summary']['#required'] = TRUE;
    $script = 'jQuery(document).ready(function(){ jQuery(".link-edit-summary").click(); });';
    drupal_add_js($script, 'inline');
  }
}