<?php
/**
* Implements hook_block_info().
*/
function gdncore_block_info() {
  $blocks = array();

  $blocks['vocabulary_terms'] = array(
    'info' => t('Vocabulary Terms'),
  );
  $blocks['vocabulary_child_terms'] = array(
    'info' => t('Vocabulary Child Terms'),
  );
  $blocks['program_more_block'] = array(
    'info' => t('Program menu more block'),
  );
  $blocks['level_one_more'] = array(
    'info' => t('Level one more block'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function gdncore_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'vocabulary_terms':
      $block['subject'] = '';
      $block['content'] = _gdncore_vocabulary_terms();
      break;
    case 'vocabulary_child_terms':
      $block['subject'] = '';
      $block['content'] = _gdncore_vocabulary_child_terms();
      break;
    case 'program_more_block':
      $block['subject'] = '';
      $block['content'] = _gdncore_program_more_block();
      break;
    case 'level_one_more':
      $block['subject'] = '';
      $block['content'] = _gdncore_level_one_more();
      break;
  }

  return $block;
}

function _gdncore_vocabulary_terms() {

  $arg1 = arg(1);
  $arg2 = arg(2);
  $arg3 = (int) arg(3);

  /*if($arg1 == 'taxonomy' && $arg2 == 'term') {
    if($arg3 > 0) {
      $termId = $arg3;
    } else if($arg3 == '' || $arg3 == NULL) {
      $termId = (int) arg(4);
    }
  }*/

  if( $arg1 == 'term' || $arg2 == 'term' ) {
    if((int) $arg2 == 0) {
      $termId = $arg3;
    } else if((int) $arg2 > 0) {
      $termId = $arg2;
    }
  }

  $objTerm = taxonomy_term_load($termId);
  $vocabMachineName = getVocabMachineName($objTerm->name);

  $tree = NULL;
  if($vocabMachineName) {
    $objVocab = taxonomy_vocabulary_machine_name_load($vocabMachineName);
    $tree = taxonomy_get_tree($objVocab->vid);
  }

  return theme('vocabulary_terms_theme', array('terms' => $tree));
}

function _gdncore_vocabulary_child_terms() {
  $arg1 = arg(1);
  $arg2 = arg(2);
  if( $arg1 == 'term' || $arg2 == 'term' ) {
    if((int) $arg2 == 0) {
      $termId = $arg3;
    } else if((int) $arg2 > 0) {
      $termId = $arg2;
    }
  }

  $objTerm = taxonomy_term_load($termId);
  //echo $termId;
  //print_r($objTerm);die;
  $tree = taxonomy_get_tree($objTerm->vid);
  return theme('vocabulary_child_terms_theme', array('terms' => $tree, 'current_term' => $objTerm->name));
}

function _gdncore_program_more_block()
{
  $pathAlias = drupal_get_path_alias(current_path());
  $capacityLink = 'program-capacity/building-research-capacity-least-developed-countries';
  $excellenceLink = 'program-capacity/development-aid-effectiveness-africa';
  $outreachLink = 'program-capacity/doing-research-assessing-environment-social-science-research-developing';
  $links = array(
    'capacity' => $capacityLink,
    'excellence' => $excellenceLink,
    'outreach' => $outreachLink,
  );

  /*switch ($pathAlias) {
    case $capacityLink:
      unset($links['capacity']);
      break;
    case $excellenceLink:
      unset($links['excellence']);
      break;
    case $outreachLink:
      unset($links['outreach']);
      break;
    default:
      break;
  }*/

  if(($key = array_search($pathAlias, $links)) !== false) {
    unset($links[$key]);
  }
  
  return theme('program_more_block', array('links' => $links));

}

function _gdncore_level_one_more() {
  
  $pathAlias = drupal_get_path_alias(current_path());
  $researchLink = 'topic/research';
  $opportunitiesLink = 'topic/opportunities';
  $resultsLink = 'topic/results';
  
  $links = array(
    'research' => $researchLink,
    'opportunities' => $opportunitiesLink,
    'results' => $resultsLink,
  );

  if(($key = array_search($pathAlias, $links)) !== false) {
    unset($links[$key]);
  }

  return theme('level_one_more', array('links' => $links));
}

/**
* Implements hook_theme().
*/
function gdncore_theme($existing, $type, $theme, $path) {
  return array(
    'vocabulary_terms_theme' => array(
      'variables' => array('taxonomies' => NULL ),
      'template' => 'vocabulary_terms',
    ),
    'vocabulary_child_terms_theme' => array(
      'variables' => array('taxonomies' => NULL, 'current_term' => NULL),
      'template' => 'vocabulary_child_terms',
    ),
    'program_more_block' => array(
      'variables' => array('links' => NULL),
      'template' => 'program_more_block',
    ),
    'level_one_more' => array(
      'variables' => array('links' => NULL),
      'template' => 'level_one_more',
    ),
  );
}


function getVocabMachineName($vocabName) {

  $vocabName = strtolower($vocabName);
  $arrVocabMapper = array(
    'research' => 'trends_categories',
    'analysis' => 'impact_categories',
    'opportunities' => 'opportunities_categories',
  );

  if($vocabName != '' && $arrVocabMapper[$vocabName] != '') {
    return $arrVocabMapper[$vocabName];
  }

  return FALSE;
}